// Generated by Selenium IDE
import org.junit.Assert;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
public class UntitledTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;
    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }
    @After
    public void tearDown() {
        driver.quit();
    }
    @Test
    public void untitled() {
        driver.get("https://www.fattal-alazman.co.il/");
        vars.put("price1", driver.findElement(By.id("lastPriceDisp")).getText());
        vars.put("price2", driver.findElement(By.xpath("(//span[@id=\'lastPriceDisp\'])[2]")).getText());
        vars.put("price3", driver.findElement(By.xpath("(//span[@id=\'lastPriceDisp\'])[3]")).getText());
        vars.put("price4", driver.findElement(By.xpath("(//span[@id=\'lastPriceDisp\'])[4]")).getText());

        Assert.assertEquals(vars.get("price1"),driver.findElement(By.id("lastPriceDisp")).getText());
        Assert.assertEquals(vars.get("price2"),driver.findElement(By.xpath("(//span[@id=\'lastPriceDisp\'])[2]")).getText());
        Assert.assertEquals(vars.get("price3"),driver.findElement(By.xpath("(//span[@id=\'lastPriceDisp\'])[3]")).getText());
        Assert.assertEquals(vars.get("price4"),driver.findElement(By.xpath("(//span[@id=\'lastPriceDisp\'])[4]")).getText());

        System.out.println(vars.get("price1").toString());
        System.out.println(vars.get("price2").toString());
        System.out.println(vars.get("price3").toString());
        System.out.println(vars.get("price4").toString());
    }
}
